import React from 'react';


 export const QuestionData = [
    {
        id: '1',
        questionText: 'Ohayou-gozaimasu (おはようございます)',
        answerOptions: [
                 { answerText: 'Good day! ', isCorrect: false },
				{ answerText: 'Good evening', isCorrect: false },
				{ answerText: 'Good morning', isCorrect: true },
				{ answerText: 'Good night', isCorrect: false },
        ],
        lesson_id: '9',
    },
    {
        id: '2',
        questionText: 'Kon’nichiwa (こんにちは)',
        answerOptions: [
                  { answerText: 'How are you?', isCorrect: false },
				{ answerText: 'Hi (during night time only)', isCorrect: false },
				{ answerText: 'Hello (during daytime only)', isCorrect: true },
				{ answerText: 'Good bye!', isCorrect: false },
        ],
        lesson_id: '8',
    },
    {
        id: '3',
        questionText: 'Konbanwa (こんばんは)',
        answerOptions: [
              { answerText: 'Good Afternoon/hello (during afternoon/afternoon)', isCorrect: false },
				{ answerText: 'Good night/hello (sweet dreams)', isCorrect: false },
				{ answerText: 'Good evening/hello (during evening/night)', isCorrect: true },
				{ answerText: 'Good morning/Hi (during day time)', isCorrect: false },
        ],
        lesson_id: '7',
    },
    {
        id: '4',
        questionText: ' Arigatou gozaimasu (ありがとうございます)',
        answerOptions: [
            { answerText: 'Your so cute', isCorrect: false },
				{ answerText: 'Welcome', isCorrect: false },
				{ answerText: 'Thank you', isCorrect: true },
				{ answerText: 'I love you', isCorrect: false },
        ],
        lesson_id: '6',
    },
    {
        id: '5',
        questionText: ' Hai (はい): ',
        answerOptions: [
            { answerText: 'Hi five!', isCorrect: false },
				{ answerText: 'Hi', isCorrect: false },
				{ answerText: 'Yes', isCorrect: true },
				{ answerText: 'No', isCorrect: false },
        ],
        lesson_id: '5',
    },
    {
        id: '6',
        questionText: 'Iie (いいえ)',
        answerOptions: [
            { answerText: 'OMG', isCorrect: false },
				{ answerText: 'Really?', isCorrect: false },
				{ answerText: 'No', isCorrect: true },
				{ answerText: 'Okay', isCorrect: false },
        ],
        lesson_id: '4',
    },
    {
        id: '7',
        questionText: 'Sumimasen (すみません): ',
        answerOptions: [
            { answerText: 'My bad', isCorrect: false },
				{ answerText: 'Welcome!', isCorrect: false },
				{ answerText: 'Excuse me', isCorrect: true },
				{ answerText: 'Sunny day', isCorrect: false },
        ],
        lesson_id: '3',
    },
    {
        id: '8',
        questionText: 'O-tazune shite mo ii desu ka? (おたずねしてもいいですか？) ',
        answerOptions: [
            { answerText: 'May you say halu', isCorrect: false },
				{ answerText: 'May you sit down?', isCorrect: false },
				{ answerText: 'May I ask you a question?', isCorrect: true },
				{ answerText: 'May I know where is the toilet?', isCorrect: false },
        ],
        lesson_id: '2',
    },
    {
        id: '9',
        questionText: 'wa doko desu ka? (~はどこにありますか？) ',
        answerOptions: [
            { answerText: 'Where to?, isCorrect: false' },
				{ answerText: 'what if?', isCorrect: false },
				{ answerText: 'Where is ~?', isCorrect: true },
				{ answerText: 'When?', isCorrect: false },
        ],
        lesson_id: '1',
    },
    {
        id: '10',
        questionText: 'Chizu o kaite moraemasu ka? (地図を書いてもらえますか？) ',
        answerOptions: [
            { answerText: 'Can you please back flip?', isCorrect: false },
				{ answerText: 'Can you point me to it?', isCorrect: false },
				{ answerText: 'Can you please draw a map for me?', isCorrect: true },
				{ answerText: 'Can I make you mine?', isCorrect: false },
        ],
        lesson_id: '1',
    },
    {
        id: '11',
        questionText: ' Koko wa doko desu ka? (ここはどこですか？) ',
        answerOptions: [
            { answerText: 'Where is my wallet? ', isCorrect: false },
				{ answerText: 'Where are you?', isCorrect: false },
				{ answerText: 'Where is this?/Where am I?', isCorrect: true },
				{ answerText: 'Where are we?', isCorrect: false },
        ],
        lesson_id: '2',
    },
    {
        id: '12',
        questionText: 'Nihongo wa hanasemasen (日本語は話せません) ',
        answerOptions: [
            { answerText: 'I cant speak fish', isCorrect: false },
				{ answerText: 'I cant speak English', isCorrect: false },
				{ answerText: 'I cant speak Japanese', isCorrect: true },
				{ answerText: 'I cant, I just cant', isCorrect: false },
        ],
        lesson_id: '3',
    },
    {
        id: '13',
        questionText: 'Mou ichido onegaishimasu (もう一度お願いします) ',
        answerOptions: [
            { answerText: 'Can I go there again?', isCorrect: false },
				{ answerText: 'Can you do that again?', isCorrect: false },
				{ answerText: 'Can you please say that again?', isCorrect: true },
				{ answerText: 'Can you make me a sandwich?', isCorrect: false },
        ],
        lesson_id: '4',
    },
    {
        id: '14',
        questionText: ' Check-in (Check-out) o onegai-shimasu (チェックイン（チェックアウト）をお願いします)',
        answerOptions: [
            { answerText: 'Where is the nearest motel?', isCorrect: false },
				{ answerText: 'I would love to be with you', isCorrect: false },
				{ answerText: 'I would like to check-in/check-out', isCorrect: true },
				{ answerText: 'I want to make a booking', isCorrect: false },
        ],
        lesson_id: '5',
    },
    {
        id: '15',
        questionText: 'Aiteiru heya wa arimasu ka? (空いている部屋はありますか？)',
        answerOptions: [
            { answerText: 'Hotel California', isCorrect: false },
				{ answerText: 'How much does it cost?', isCorrect: false },
				{ answerText: ' Are there any rooms available?', isCorrect: true },
				{ answerText: 'Are there room for sale?', isCorrect: false },
        ],
        lesson_id: '6',
    },
    {
        id: '16',
        questionText: 'Kore wa nan no ryokin desu ka? (これは何の料金ですか？) ',
        answerOptions: [
            { answerText: 'Where is the money?', isCorrect: false },
				{ answerText: 'What is the meaning of this?', isCorrect: false },
				{ answerText: 'What is this charge for?', isCorrect: true },
				{ answerText: 'How dare you?', isCorrect: false },
        ],
        lesson_id: '7',
    },
    {
        id: '17',
        questionText: 'Daiyokujou wa doko desu ka? (大浴場はどこですか？) ',
        answerOptions: [
            { answerText: 'Where can I dump my waste?', isCorrect: false },
				{ answerText: 'Where is the ani doro?', isCorrect: false },
				{ answerText: 'Where is the public bath?', isCorrect: true },
				{ answerText: 'Can I pee anywhere?', isCorrect: false },
        ],
        lesson_id: '8',
    },
    {
        id: '18',
        questionText: 'Chizu wa arimasu ka? (地図はありますか？) ',
        answerOptions: [
            { answerText: 'Do you know?', isCorrect: false },
				{ answerText: 'Do you have the road?', isCorrect: false },
				{ answerText: 'Do you have a map?', isCorrect: true },
				{ answerText: 'Do you have a GPS?', isCorrect: false },
        ],
        lesson_id: '9',
    },
    {
        id: '19',
        questionText: 'Chikaku ni o-susume no resutoran wa arimasu ka? (近くにおすすめのレストランはありますか？) ',
        answerOptions: [
            { answerText: 'I want to eat kwek kwek', isCorrect: false },
				{ answerText: 'Are there any tasty food?', isCorrect: false },
				{ answerText: 'Are there any recommended restaurants nearby?', isCorrect: true },
				{ answerText: 'I am hungy mommy!', isCorrect: false },
        ],
        lesson_id: '1',
    },
    {
        id: '20',
        questionText: 'Eigo no tsua wo shokai shite kudasai (英語のツアーを紹介してください)',
        answerOptions: [
            { answerText: 'Please  about the route', isCorrect: false },
				{ answerText: 'Please tell me to stop', isCorrect: false },
				{ answerText: 'Please tell me about the English tour(s).', isCorrect: true },
				{ answerText: 'Please tour me around jack!', isCorrect: false },
        ],
        lesson_id: '2',
    },
    {
        id: '21',
        questionText: 'Heya ni kagi wo wasuremashita (部屋にカギを忘れました) ',
        answerOptions: [
            { answerText: 'I forget my brain', isCorrect: false },
				{ answerText: 'I forgot my self', isCorrect: false },
				{ answerText: 'I forgot my key in the room', isCorrect: true },
				{ answerText: 'I forgot my wallet', isCorrect: false },
        ],
        lesson_id: '3',
    },
    {
        id: '22',
        questionText: 'Menu o kudasai (メニューをください) ',
        answerOptions: [
            { answerText: 'Lets eat now please', isCorrect: false },
				{ answerText: 'Please give me food', isCorrect: false },
				{ answerText: 'Please give me a menu', isCorrect: true },
				{ answerText: 'Please cook for me', isCorrect: false },
        ],
        lesson_id: '4',
    },
    {
        id: '23',
        questionText: 'Chumon o onegashimasu (注文をお願いします) ',
        answerOptions: [
            { answerText: 'Im ready to eat all', isCorrect: false },
				{ answerText: 'Im not yet ready', isCorrect: false },
				{ answerText: 'Im ready to order', isCorrect: true },
				{ answerText: 'Im ready to mingle', isCorrect: false },
        ],
        lesson_id: '5',
    },
    {
        id: '24',
        questionText: 'O-susume no menu wa dore desu ka? (おすすめのメニュ―はどれですか？) ',
        answerOptions: [
            { answerText: 'Where is the foodk', isCorrect: false },
				{ answerText: 'What items do you want?', isCorrect: false },
				{ answerText: 'What menu item do you recommend?', isCorrect: true },
				{ answerText: 'There is nothing I can order?', isCorrect: false },
        ],
        lesson_id: '6',
    },
    {
        id: '25',
        questionText: 'Kore wa nan desu ka? (これは何ですか？): ',
        answerOptions: [
            { answerText: 'What isda?', isCorrect: false },
				{ answerText: 'What is that?', isCorrect: false },
				{ answerText: 'What is this?', isCorrect: true },
				{ answerText: 'What to see?', isCorrect: false },
        ],
        lesson_id: '7',
    },
    {
        id: '26',
        questionText: 'Kore o onegaishimasu (これをお願いします) ',
        answerOptions: [
            { answerText: 'I’d like fly', isCorrect: false },
				{ answerText: 'I’d like dance', isCorrect: false },
				{ answerText: 'I’d like (to order) this, please', isCorrect: true },
				{ answerText: 'I’d like bugy', isCorrect: false },
        ],
        lesson_id: '8',
    },
    {
        id: '27',
        questionText: 'Kohi wa tsukimasu ka? (コーヒーはつきますか？) ',
        answerOptions: [
            { answerText: 'Does it include a bubble gum?', isCorrect: false },
				{ answerText: 'Does it have a milk??', isCorrect: false },
				{ answerText: 'Does it include coffee?', isCorrect: true },
				{ answerText: 'Does it have chocolate', isCorrect: false },
        ],
        lesson_id: '9',
    },
    {
        id: '28',
        questionText: 'Mizu o onegaishimasu (水をお願いします)',
        answerOptions: [
            { answerText: 'Please give me some kiss', isCorrect: false },
				{ answerText: 'Please give me some love', isCorrect: false },
				{ answerText: 'Please give me some water', isCorrect: true },
				{ answerText: 'Please give me some gatorade', isCorrect: false },
        ],
        lesson_id: '10',
    },
    {
        id: '29',
        questionText: 'Toire wa doko desu ka? (トイレはどこですか？) ',
        answerOptions: [
            { answerText: 'Where is the vortex?', isCorrect: false },
				{ answerText: 'Where is the room?', isCorrect: false },
				{ answerText: 'Where is the bathroom?', isCorrect: true },
				{ answerText: 'Where is the living room?', isCorrect: false },
        ],
        lesson_id: '1',
    },
    {
        id: '30',
        questionText: 'The Caspital City of France?',
        answerOptions: [
            { answerText: 'New York', isCorrect: false },
				{ answerText: 'London', isCorrect: false },
				{ answerText: 'Paris', isCorrect: true },
				{ answerText: 'Dublin', isCorrect: false },
        ],
        lesson_id: '2',
    },
    {
        id: '31',
        questionText: 'Itadakimasu (いただきます)',
        answerOptions: [
            { answerText: 'Phrase said after your angry', isCorrect: false },
				{ answerText: 'Phrase said before going super sayan', isCorrect: false },
				{ answerText: 'Phrase said before eating food', isCorrect: true },
				{ answerText: 'Phrase said before peeing', isCorrect: false },
        ],
        lesson_id: '3',
    },
    {
        id: '32',
        questionText: 'Gochisosama deshita (ごちそうさまでした)',
        answerOptions: [
            { answerText: 'Phrase said after doing a back flip', isCorrect: false },
				{ answerText: 'Phrase said after going to the toilet', isCorrect: false },
				{ answerText: 'Phrase said after eating; also means “Thank you for the meal', isCorrect: true },
				{ answerText: 'Phrase said after doing a karate chop', isCorrect: false },
        ],
        lesson_id: '4',
    },
    {
        id: '33',
        questionText: 'O-kaikei o onegaishimasu (お会計をお願いします)',
        answerOptions: [
            { answerText: 'wrong please', isCorrect: false },
				{ answerText: 'check mate', isCorrect: false },
				{ answerText: 'Check please', isCorrect: true },
				{ answerText: 'I pay for all', isCorrect: false },
        ],
        lesson_id: '5',
    },
    {
        id: '34',
        questionText: 'Kippu uriba wa doko desu ka? (切符売り場はどこですか？)',
        answerOptions: [
                  { answerText: 'Where can I buy a beer?', isCorrect: false },
				{ answerText: 'Where can I buy  cap?', isCorrect: false },
				{ answerText: 'Where can I buy tickets?', isCorrect: true },
				{ answerText: 'Where can I buy a hotel?', isCorrect: false },
        ],
        lesson_id: '6',
    },
    {
        id: '35',
        questionText: '~ ni wa dou ikeba ii desu ka? (にはどう行けばいいですか？): ',
        answerOptions: [
            { answerText: 'How do I make you mine?', isCorrect: false },
				{ answerText: 'How do I turn to a hulk?', isCorrect: false },
				{ answerText: 'How do I get to ~?', isCorrect: true },
				{ answerText: 'How do we fall inlove', isCorrect: false },
        ],
        lesson_id: '7',
    },
    {
        id: '36',
        questionText: 'made no kippu o kudasai (までの切符をください):',
        answerOptions: [
            { answerText: 'Please take me to the moon', isCorrect: false },
				{ answerText: 'Please dont?', isCorrect: false },
				{ answerText: ' Please give me a ticket to ~', isCorrect: true },
				{ answerText: 'Please give me my shoe', isCorrect: false },
        ],
        lesson_id: '8',
    },
]